"""add new columns

Revision ID: 28cdcdfee275
Revises: d2884a0dccae
Create Date: 2026-02-03 09:16:33.715494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '28cdcdfee275'
down_revision: Union[str, Sequence[str], None] = 'd2884a0dccae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_price',
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=24, scale=8), nullable=False),
    sa.Column('as_of', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index('idx_asset_price_asof', 'asset_price', ['as_of'], unique=False)
    op.create_table('prompts',
    sa.Column('prompt_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_index('idx_prompts_active', 'prompts', ['is_active'], unique=False)
    op.create_index('uk_prompts_key', 'prompts', ['key'], unique=True)
    op.create_table('user_portfolio',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=24, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('avg_buy_price', sa.DECIMAL(precision=24, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'asset_id')
    )
    op.create_index('idx_user_portfolio_asset', 'user_portfolio', ['asset_id'], unique=False)
    op.create_index('idx_user_portfolio_user', 'user_portfolio', ['user_id'], unique=False)
    op.create_table('village_prompts',
    sa.Column('village_id', sa.BigInteger(), nullable=False),
    sa.Column('prompt_id', sa.BigInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('village_id', 'prompt_id')
    )
    op.create_index('idx_village_prompts_order', 'village_prompts', ['village_id', 'sort_order'], unique=False)
    op.create_index('idx_village_prompts_prompt', 'village_prompts', ['prompt_id'], unique=False)
    op.drop_table('risk_profiles')
    op.drop_table('user_settings')
    op.drop_index(op.f('idx_news_item_assets_asset'), table_name='news_item_assets')
    op.drop_table('news_item_assets')
    op.drop_index(op.f('idx_neighbor_reco_user'), table_name='neighbor_recommendations')
    op.drop_table('neighbor_recommendations')
    op.drop_index(op.f('idx_briefing_news_news'), table_name='briefing_news_links')
    op.drop_table('briefing_news_links')
    op.drop_index(op.f('idx_village_metrics_date'), table_name='village_metrics_daily')
    op.drop_table('village_metrics_daily')
    op.drop_table('neighbor_item_assets')
    op.drop_index(op.f('idx_neighbor_items_reco'), table_name='neighbor_recommendation_items')
    op.drop_table('neighbor_recommendation_items')
    op.drop_index(op.f('idx_news_published'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('idx_briefings_user_time'), table_name='briefings')
    op.drop_index(op.f('idx_briefings_village'), table_name='briefings')
    op.drop_table('briefings')
    op.add_column('assets', sa.Column('asset_id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column('assets', sa.Column('symbol', sa.String(length=32), nullable=False))
    op.add_column('assets', sa.Column('country_code', sa.String(length=2), nullable=False))
    op.add_column('assets', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('assets', 'name',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('assets', 'asset_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('STOCK', 'ETF', name='asset_type'),
               existing_nullable=False)
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('idx_assets_ticker'), table_name='assets')
    op.create_index('idx_assets_country', 'assets', ['country_code'], unique=False)
    op.create_index('idx_assets_type', 'assets', ['asset_type'], unique=False)
    op.create_index('uk_assets_symbol', 'assets', ['symbol'], unique=True)
    op.drop_column('assets', 'id')
    op.drop_column('assets', 'currency')
    op.drop_column('assets', 'ticker')
    op.drop_column('assets', 'market')
    op.add_column('users', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('mda_mode', sa.Enum('PRE', 'POST', name='mda_mode'), server_default=sa.text("'PRE'"), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'id')
    op.drop_column('users', 'name')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'theme')
    op.alter_column('village_assets', 'village_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('village_assets', 'asset_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('village_assets', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('idx_village_assets_village'), table_name='village_assets')
    op.drop_constraint(op.f('village_assets_ibfk_2'), 'village_assets', type_='foreignkey')
    op.drop_constraint(op.f('village_assets_ibfk_1'), 'village_assets', type_='foreignkey')
    op.drop_column('village_assets', 'quantity')
    op.drop_column('village_assets', 'value')
    op.drop_column('village_assets', 'id')
    op.drop_column('village_assets', 'updated_at')
    op.drop_column('village_assets', 'avg_price')
    op.add_column('villages', sa.Column('village_id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column('villages', sa.Column('village_type', sa.Enum('SYSTEM', 'CUSTOM', name='village_type'), server_default=sa.text("'SYSTEM'"), nullable=False))
    op.add_column('villages', sa.Column('ai_one_liner', sa.String(length=256), nullable=True))
    op.add_column('villages', sa.Column('as_of', sa.TIMESTAMP(), nullable=True))
    op.alter_column('villages', 'user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('villages', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('villages', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('villages', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.create_index('idx_villages_user_type', 'villages', ['user_id', 'village_type'], unique=False)
    op.drop_constraint(op.f('villages_ibfk_1'), 'villages', type_='foreignkey')
    op.drop_column('villages', 'type')
    op.drop_column('villages', 'id')
    op.drop_column('villages', 'last_briefing_read')
    op.drop_column('villages', 'goal')
    op.drop_column('villages', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('villages', sa.Column('icon', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('villages', sa.Column('goal', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('villages', sa.Column('last_briefing_read', mysql.DATETIME(), nullable=True))
    op.add_column('villages', sa.Column('id', mysql.CHAR(length=36), nullable=False))
    op.add_column('villages', sa.Column('type', mysql.VARCHAR(length=30), nullable=True))
    op.create_foreign_key(op.f('villages_ibfk_1'), 'villages', 'users', ['user_id'], ['id'])
    op.drop_index('idx_villages_user_type', table_name='villages')
    op.alter_column('villages', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('villages', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('villages', 'name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('villages', 'user_id',
               existing_type=sa.BigInteger(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_column('villages', 'as_of')
    op.drop_column('villages', 'ai_one_liner')
    op.drop_column('villages', 'village_type')
    op.drop_column('villages', 'village_id')
    op.add_column('village_assets', sa.Column('avg_price', mysql.DECIMAL(precision=20, scale=6), nullable=True))
    op.add_column('village_assets', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.add_column('village_assets', sa.Column('id', mysql.CHAR(length=36), nullable=False))
    op.add_column('village_assets', sa.Column('value', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('village_assets', sa.Column('quantity', mysql.DECIMAL(precision=20, scale=6), nullable=True))
    op.create_foreign_key(op.f('village_assets_ibfk_1'), 'village_assets', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key(op.f('village_assets_ibfk_2'), 'village_assets', 'villages', ['village_id'], ['id'])
    op.create_index(op.f('idx_village_assets_village'), 'village_assets', ['village_id'], unique=False)
    op.alter_column('village_assets', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('village_assets', 'asset_id',
               existing_type=sa.BigInteger(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('village_assets', 'village_id',
               existing_type=sa.BigInteger(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.add_column('users', sa.Column('theme', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('users', sa.Column('profile_image_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('users', sa.Column('id', mysql.CHAR(length=36), nullable=False))
    op.alter_column('users', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.drop_column('users', 'mda_mode')
    op.drop_column('users', 'user_id')
    op.add_column('assets', sa.Column('market', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('assets', sa.Column('ticker', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('assets', sa.Column('currency', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('assets', sa.Column('id', mysql.CHAR(length=36), nullable=False))
    op.drop_index('uk_assets_symbol', table_name='assets')
    op.drop_index('idx_assets_type', table_name='assets')
    op.drop_index('idx_assets_country', table_name='assets')
    op.create_index(op.f('idx_assets_ticker'), 'assets', ['ticker'], unique=False)
    op.alter_column('assets', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('assets', 'asset_type',
               existing_type=sa.Enum('STOCK', 'ETF', name='asset_type'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('assets', 'name',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_column('assets', 'updated_at')
    op.drop_column('assets', 'country_code')
    op.drop_column('assets', 'symbol')
    op.drop_column('assets', 'asset_id')
    op.create_table('briefings',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('time_slot', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('target_scope', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('village_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('tts_audio_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('generated_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='briefings_ibfk_1'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], name='briefings_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_briefings_village'), 'briefings', ['village_id'], unique=False)
    op.create_index(op.f('idx_briefings_user_time'), 'briefings', ['user_id', 'time_slot'], unique=False)
    op.create_table('news_items',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('summary', mysql.TEXT(), nullable=True),
    sa.Column('source', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=800), nullable=True),
    sa.Column('published_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_news_published'), 'news_items', ['published_at'], unique=False)
    op.create_table('neighbor_recommendation_items',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('recommendation_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('icon', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('reason', mysql.TEXT(), nullable=True),
    sa.Column('correlation', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['neighbor_recommendations.id'], name='neighbor_recommendation_items_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_neighbor_items_reco'), 'neighbor_recommendation_items', ['recommendation_id'], unique=False)
    op.create_table('neighbor_item_assets',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('recommendation_item_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('asset_id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('neighbor_item_assets_ibfk_1')),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['neighbor_recommendation_items.id'], name=op.f('neighbor_item_assets_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('village_metrics_daily',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('village_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('metric_date', sa.DATE(), nullable=False),
    sa.Column('total_value', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('return_rate', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('allocation', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], name=op.f('village_metrics_daily_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_village_metrics_date'), 'village_metrics_daily', ['village_id', 'metric_date'], unique=False)
    op.create_table('briefing_news_links',
    sa.Column('briefing_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('news_item_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('relevance_score', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['briefing_id'], ['briefings.id'], name=op.f('briefing_news_links_ibfk_1')),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], name=op.f('briefing_news_links_ibfk_2')),
    sa.PrimaryKeyConstraint('briefing_id', 'news_item_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_briefing_news_news'), 'briefing_news_links', ['news_item_id'], unique=False)
    op.create_table('neighbor_recommendations',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('neighbor_recommendations_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_neighbor_reco_user'), 'neighbor_recommendations', ['user_id'], unique=False)
    op.create_table('news_item_assets',
    sa.Column('news_item_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('asset_id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('news_item_assets_ibfk_1')),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], name=op.f('news_item_assets_ibfk_2')),
    sa.PrimaryKeyConstraint('news_item_id', 'asset_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_news_item_assets_asset'), 'news_item_assets', ['asset_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('briefing_time', mysql.TIME(), nullable=False),
    sa.Column('tts_speed', mysql.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('timezone', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('risk_profiles',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('risk_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('risk_profiles_ibfk_1')),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index('idx_village_prompts_prompt', table_name='village_prompts')
    op.drop_index('idx_village_prompts_order', table_name='village_prompts')
    op.drop_table('village_prompts')
    op.drop_index('idx_user_portfolio_user', table_name='user_portfolio')
    op.drop_index('idx_user_portfolio_asset', table_name='user_portfolio')
    op.drop_table('user_portfolio')
    op.drop_index('uk_prompts_key', table_name='prompts')
    op.drop_index('idx_prompts_active', table_name='prompts')
    op.drop_table('prompts')
    op.drop_index('idx_asset_price_asof', table_name='asset_price')
    op.drop_table('asset_price')
    # ### end Alembic commands ###
