"""Initial migration

Revision ID: d2884a0dccae
Revises: 
Create Date: 2026-02-02 11:13:15.390965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2884a0dccae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=20), nullable=False),
    sa.Column('market', sa.VARCHAR(length=20), nullable=False),
    sa.Column('asset_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_ticker', 'assets', ['ticker'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=80), nullable=True),
    sa.Column('url', sa.VARCHAR(length=800), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_published', 'news_items', ['published_at'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('briefing_time', sa.TIME(), nullable=False),
    sa.Column('tts_speed', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=50), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('profile_image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('theme', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neighbor_recommendations',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_neighbor_reco_user', 'neighbor_recommendations', ['user_id'], unique=False)
    op.create_table('news_item_assets',
    sa.Column('news_item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('asset_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('news_item_id', 'asset_id')
    )
    op.create_index('idx_news_item_assets_asset', 'news_item_assets', ['asset_id'], unique=False)
    op.create_table('risk_profiles',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('risk_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('villages',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), nullable=True),
    sa.Column('goal', sa.VARCHAR(length=200), nullable=True),
    sa.Column('last_briefing_read', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_villages_user', 'villages', ['user_id'], unique=False)
    op.create_table('briefings',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('time_slot', sa.Enum('MORNING', 'EVENING', name='timeslot', native_enum=False, length=20), nullable=False),
    sa.Column('target_scope', sa.Enum('ALL_VILLAGES', 'SINGLE_VILLAGE', name='targetscope', native_enum=False, length=20), nullable=False),
    sa.Column('village_id', sa.CHAR(length=36), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('tts_audio_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_briefings_user_time', 'briefings', ['user_id', 'time_slot'], unique=False)
    op.create_index('idx_briefings_village', 'briefings', ['village_id'], unique=False)
    op.create_table('neighbor_recommendation_items',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('recommendation_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('correlation', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['neighbor_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_neighbor_items_reco', 'neighbor_recommendation_items', ['recommendation_id'], unique=False)
    op.create_table('village_assets',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('village_id', sa.CHAR(length=36), nullable=False),
    sa.Column('asset_id', sa.CHAR(length=36), nullable=False),
    sa.Column('value', sa.BIGINT(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=6), nullable=True),
    sa.Column('avg_price', sa.DECIMAL(precision=20, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_village_assets_asset', 'village_assets', ['asset_id'], unique=False)
    op.create_index('idx_village_assets_village', 'village_assets', ['village_id'], unique=False)
    op.create_table('village_metrics_daily',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.CHAR(length=36), nullable=False),
    sa.Column('metric_date', sa.DATE(), nullable=False),
    sa.Column('total_value', sa.BIGINT(), nullable=False),
    sa.Column('return_rate', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('allocation', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_village_metrics_date', 'village_metrics_daily', ['village_id', 'metric_date'], unique=False)
    op.create_table('briefing_news_links',
    sa.Column('briefing_id', sa.CHAR(length=36), nullable=False),
    sa.Column('news_item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('relevance_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['briefing_id'], ['briefings.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('briefing_id', 'news_item_id')
    )
    op.create_index('idx_briefing_news_news', 'briefing_news_links', ['news_item_id'], unique=False)
    op.create_table('neighbor_item_assets',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('recommendation_item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('asset_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['neighbor_recommendation_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neighbor_item_assets')
    op.drop_index('idx_briefing_news_news', table_name='briefing_news_links')
    op.drop_table('briefing_news_links')
    op.drop_index('idx_village_metrics_date', table_name='village_metrics_daily')
    op.drop_table('village_metrics_daily')
    op.drop_index('idx_village_assets_village', table_name='village_assets')
    op.drop_index('idx_village_assets_asset', table_name='village_assets')
    op.drop_table('village_assets')
    op.drop_index('idx_neighbor_items_reco', table_name='neighbor_recommendation_items')
    op.drop_table('neighbor_recommendation_items')
    op.drop_index('idx_briefings_village', table_name='briefings')
    op.drop_index('idx_briefings_user_time', table_name='briefings')
    op.drop_table('briefings')
    op.drop_index('idx_villages_user', table_name='villages')
    op.drop_table('villages')
    op.drop_table('risk_profiles')
    op.drop_index('idx_news_item_assets_asset', table_name='news_item_assets')
    op.drop_table('news_item_assets')
    op.drop_index('idx_neighbor_reco_user', table_name='neighbor_recommendations')
    op.drop_table('neighbor_recommendations')
    op.drop_table('users')
    op.drop_table('user_settings')
    op.drop_index('idx_news_published', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index('idx_assets_ticker', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
